local_url: https://passport.jd.com/new/login.aspx
api_url: http://www.baidu.com/
browser: chrome
num: 800
account: 18816531992
password: zq921210
goods: 华为
log:
    file_name: test.log      # 输出日志文件名
    backup: 5                # 备份名
    console_level: WARNING  # 控制台输出等级
    file_level: DEBUG       # 文件输出等级
    pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'  # 打印输出格式




